name: 'Checkout, Setup Node and install dependencies'
description: 'Checkout, Setup Node and install dependencies'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm i
      shell: bash
