name: 'Setup Node and install dependencies'
description: 'Setup Node and install dependencies'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      run: npm i
      shell: bash
