name: Mark stale issues
on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 01:30 UTC
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is missing information/reproduction for 3 weeks with no activity. Please provide the required information/reproduction or this issue will be closed in 7 days.'
          days-before-stale: 21
          only-labels: 'Missing reproduction,Missing information'
          days-before-pr-stale: -1  # Exclude PRs
          days-before-pr-close: -1  # Exclude PRs
